insert into mensagens (codigo, mensagem) values(1001 ,"Sistema iniciado.");
insert into mensagens (codigo, mensagem) values(1002 ,"Sistema encerrado.");
insert into mensagens (codigo, mensagem) values(2001 ,"Autenticação etapa 1 iniciada.");
insert into mensagens (codigo, mensagem) values(2002 ,"Autenticação etapa 1 encerrada.");
insert into mensagens (codigo, mensagem) values(2003 ,"Login name <login_name> identificado com acesso liberado.");
insert into mensagens (codigo, mensagem) values(2004 ,"Login name <login_name> identificado com acesso bloqueado.");
insert into mensagens (codigo, mensagem) values(2005 ,"Login name <login_name> não identificado.");
insert into mensagens (codigo, mensagem) values(3001 ,"Autenticação etapa 2 iniciada para <login_name>.");
insert into mensagens (codigo, mensagem) values(3002 ,"Autenticação etapa 2 encerrada para <login_name>.");
insert into mensagens (codigo, mensagem) values(3003 ,"Senha pessoal verificada positivamente para <login_name>.");
insert into mensagens (codigo, mensagem) values(3004 ,"Primeiro erro da senha pessoal contabilizado para <login_name>.");
insert into mensagens (codigo, mensagem) values(3005 ,"Segundo erro da senha pessoal contabilizado para <login_name>.");
insert into mensagens (codigo, mensagem) values(3006 ,"Terceiro erro da senha pessoal contabilizado para <login_name>.");
insert into mensagens (codigo, mensagem) values(3007 ,"Acesso do usuario <login_name> bloqueado pela autenticação etapa 2.");
insert into mensagens (codigo, mensagem) values(4001 ,"Autenticação etapa 3 iniciada para <login_name>.");
insert into mensagens (codigo, mensagem) values(4002 ,"Autenticação etapa 3 encerrada para <login_name>.");
insert into mensagens (codigo, mensagem) values(4003 ,"Chave privada verificada positivamente para <login_name>.");
insert into mensagens (codigo, mensagem) values(4004 ,"Chave privada verificada negativamente para <login_name> (caminho inválido).");
insert into mensagens (codigo, mensagem) values(4005 ,"Chave privada verificada negativamente para <login_name> (frase secreta inválida).");
insert into mensagens (codigo, mensagem) values(4006 ,"Chave privada verificada negativamente para <login_name> (assinatura digital inválida).");
insert into mensagens (codigo, mensagem) values(4007 ,"Acesso do usuario <login_name> bloqueado pela autenticação etapa 3.");
insert into mensagens (codigo, mensagem) values(5001 ,"Tela principal apresentada para <login_name>.");
insert into mensagens (codigo, mensagem) values(5002 ,"Opção 1 do menu principal selecionada por <login_name>.");
insert into mensagens (codigo, mensagem) values(5003 ,"Opção 2 do menu principal selecionada por <login_name>.");
insert into mensagens (codigo, mensagem) values(5004 ,"Opção 3 do menu principal selecionada por <login_name>.");
insert into mensagens (codigo, mensagem) values(5005 ,"Opção 4 do menu principal selecionada por <login_name>.");
insert into mensagens (codigo, mensagem) values(6001 ,"Tela de cadastro apresentada para <login_name>.");
insert into mensagens (codigo, mensagem) values(6002 ,"Botão cadastrar pressionado por <login_name>.");
insert into mensagens (codigo, mensagem) values(6003 ,"Senha pessoal inválida fornecida por <login_name>.");
insert into mensagens (codigo, mensagem) values(6004 ,"Caminho do certificado digital inválido fornecido por <login_name>.");
insert into mensagens (codigo, mensagem) values(6005 ,"Confirmação de dados aceita por <login_name>.");
insert into mensagens (codigo, mensagem) values(6006 ,"Confirmação de dados rejeitada por <login_name>.");
insert into mensagens (codigo, mensagem) values(6007 ,"Botão voltar de cadastro para o menu principal pressionado por <login_name>.");
insert into mensagens (codigo, mensagem) values(7001 ,"Tela de alteração da senha pessoal e certificado apresentada para <login_name>.");
insert into mensagens (codigo, mensagem) values(7002 ,"Senha pessoal inválida fornecida por <login_name>.");
insert into mensagens (codigo, mensagem) values(7003 ,"Caminho do certificado digital inválido fornecido por <login_name>.");
insert into mensagens (codigo, mensagem) values(7004 ,"Confirmação de dados aceita por <login_name>.");
insert into mensagens (codigo, mensagem) values(7005 ,"Confirmação de dados rejeitada por <login_name>.");
insert into mensagens (codigo, mensagem) values(7006 ,"Botão voltar de carregamento para o menu principal pressionado por <login_name>.");
insert into mensagens (codigo, mensagem) values(8001 ,"Tela de consulta de arquivos secretos apresentada para <login_name>.");
insert into mensagens (codigo, mensagem) values(8002 ,"Botão voltar de consulta para o menu principal pressionado por <login_name>.");
insert into mensagens (codigo, mensagem) values(8003 ,"Botão Listar de consulta pressionado por <login_name>.");
insert into mensagens (codigo, mensagem) values(8004 ,"Caminho de pasta inválido fornecido por <login_name>.");
insert into mensagens (codigo, mensagem) values(8005 ,"Arquivo de índice decriptado com sucesso para <login_name>.");
insert into mensagens (codigo, mensagem) values(8006 ,"Arquivo de índice verificado (integridade e autenticidade) com sucesso para <login_name>.");
insert into mensagens (codigo, mensagem) values(8007 ,"Falha na decriptação do arquivo de índice para <login_name>.");
insert into mensagens (codigo, mensagem) values(8008 ,"Falha na verificação (integridade e autenticidade) do arquivo de índice para <login_name>.");
insert into mensagens (codigo, mensagem) values(8009 ,"Lista de arquivos presentes no índice apresentada para <login_name>.");
insert into mensagens (codigo, mensagem) values(8010 ,"Arquivo <arq_name> selecionado por <login_name> para decriptação.");
insert into mensagens (codigo, mensagem) values(8011 ,"Acesso permitido ao arquivo <arq_name> para <login_name>.");
insert into mensagens (codigo, mensagem) values(8012 ,"Acesso negado ao arquivo <arq_name> para <login_name>.");
insert into mensagens (codigo, mensagem) values(8013 ,"Arquivo <arq_name> decriptado com sucesso para <login_name>.");
insert into mensagens (codigo, mensagem) values(8014 ,"Arquivo <arq_name> verificado (integridade e autenticidade) com sucesso para <login_name>.");
insert into mensagens (codigo, mensagem) values(8015 ,"Falha na decriptação do arquivo <arq_name> para <login_name>.");
insert into mensagens (codigo, mensagem) values(8016 ,"Falha na verificação (integridade e autenticidade) do arquivo <arq_name> para <login_name>.");
insert into mensagens (codigo, mensagem) values(9001 ,"Tela de saída apresentada para <login_name>.");
insert into mensagens (codigo, mensagem) values(9002 ,"Saída não liberada por falta de one-time password para <login_name>.");
insert into mensagens (codigo, mensagem) values(9003 ,"Botão sair pressionado por <login_name>.");
insert into mensagens (codigo, mensagem) values(9004 ,"Botão voltar de sair para o menu principal pressionado por <login_name>.");